<?php

return [
    // UK zone
    'uk' => [
        "UK"
    ],
    // EU zone
    'eu' => [
        'AL',
        'AD',
        'AM',
        'AT',
        'AZ',
        'BY',
        'BE',
        'BA',
        'BG',
        'HR',
        'CY',
        'CZ',
        'DK',
        'EE',
        'FO',
        'FI',
        'FR',
        'GE',
        'DE',
        'GI',
        'GR',
        'GL',
        'HU',
        'IS',
        'IT',
        'KZ',
        'KG',
        'LV',
        'LI',
        'LT',
        'LU',
        'MK',
        'MT',
        'MD',
        'MC',
        'ME',
        'NL',
        'NO',
        'PL',
        'PT',
        'RO',
        'RU',
        'SM',
        'RS',
        'SK',
        'ES',
        'SE',
        'CH',
        'TJ',
        'TR',
        'TM',
        'UA',
        'UZ',
        'VA',
    ],
    // Zone 1 will be true if non of them in this list

    // Zone 2
    'z2' => [
        'AU',
        'CX',
        'FJ',
        'KI',
        'NZ',
        'SG',
        'TO',
        'CC',
        'PF',
        'MO',
        'PG',
        'SB',
        'TV',
        'IO',
        'CK',
        'TF',
        'NR',
        'NU',
        'LA',
        'NC',
        'NF',
        'PN',
        'TK',
        'SO',
    ]
];